[package]
name = "line-sticker-dw"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Wayne Hong <admin@halice.art>"]

[profile.release]
lto = true
strip = true
opt-level = "z"
panic = "abort"
codegen-units = 1

[dependencies]
anyhow = "1.0.100"
async-compat = "0.2.5"
reqwest = "0.13.1"
scraper = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
smol = { version = "2.0" }
futures = "0.3"
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
